Fix sigjmp_buf/jmp_buf mismatches.
Broke the bionic build:

  external/toybox/toys/net/netcat.c:188:37: error: incompatible pointer types assigning to 'sigjmp_buf *' (aka 'long (*)[33]') from 'jmp_buf *' (aka 'long (*)[32]') [-Werror,-Wincompatible-pointer-types]
          if (toys.optflags&FLAG_L) NOEXIT(child = XVFORK());
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
  external/toybox/lib/lib.h:375:19: note: expanded from macro 'NOEXIT'
  #define NOEXIT(x) WOULD_EXIT(_noexit_res, x)
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
  external/toybox/lib/lib.h:367:16: note: expanded from macro 'WOULD_EXIT'
    toys.rebound = &_noexit; \
                 ^ ~~~~~~~~
  1 error generated.