Fix build when wchar_t is unsigned.
  external/toybox/lib/linestack.c:84:5: error: conflicting types for 'crunch_str'
  int crunch_str(char **str, int width, FILE *out, char *escmore,
      ^
  external/toybox/lib/lib.h:228:5: note: previous declaration is here
  int crunch_str(char **str, int width, FILE *out, char *escmore,
      ^

I'm not sure whether the interface was intended to be wchar_t or int, but
switching to int is the smaller change...