glibc on mips is missing SIGSTKFLT
Do not therefore assume it being available linuxwide

Fixes
| lib/portability.c:433:3: error: use of undeclared identifier 'SIGSTKFLT'
|   SIGNIFY(STKFLT), SIGNIFY(POLL), SIGNIFY(PWR),
|   ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>